const List<Map<String, dynamic>> ayahsList = [
  {
    "number": 1,
    "name": " ٱلْفَاتِحَةِ",
    "englishName": "Al-Faatiha",
    "englishNameTranslation": "The Opening",
    "numberOfAyahs": 7,
    "revelationType": "مكية",
  },
  {
    "number": 2,
    "name": " البَقَرَةِ",
    "englishName": "Al-Baqara",
    "englishNameTranslation": "The Cow",
    "numberOfAyahs": 286,
    "revelationType": "مدنية",
  },
  {
    "number": 3,
    "name": " آلِ عِمۡرَانَ",
    "englishName": "Aal-i-Imraan",
    "englishNameTranslation": "The Family of Imraan",
    "numberOfAyahs": 200,
    "revelationType": "مدنية",
  },
  {
    "number": 4,
    "name": " النِّسَاءِ",
    "englishName": "An-Nisaa",
    "englishNameTranslation": "The Women",
    "numberOfAyahs": 176,
    "revelationType": "مدنية",
  },
  {
    "number": 5,
    "name": " المَائـِدَةِ",
    "englishName": "Al-Maaida",
    "englishNameTranslation": "The Table",
    "numberOfAyahs": 120,
    "revelationType": "مدنية",
  },
  {
    "number": 6,
    "name": " الأَنۡعَامِ",
    "englishName": "Al-An'aam",
    "englishNameTranslation": "The Cattle",
    "numberOfAyahs": 165,
    "revelationType": "مكية",
  },
  {
    "number": 7,
    "name": " الأَعۡرَافِ",
    "englishName": "Al-A'raaf",
    "englishNameTranslation": "The Heights",
    "numberOfAyahs": 206,
    "revelationType": "مكية",
  },
  {
    "number": 8,
    "name": " الأَنفَالِ",
    "englishName": "Al-Anfaal",
    "englishNameTranslation": "The Spoils of War",
    "numberOfAyahs": 75,
    "revelationType": "مدنية",
  },
  {
    "number": 9,
    "name": " التَّوۡبَةِ",
    "englishName": "At-Tawba",
    "englishNameTranslation": "The Repentance",
    "numberOfAyahs": 129,
    "revelationType": "مدنية",
  },
  {
    "number": 10,
    "name": " يُونُسَ",
    "englishName": "Yunus",
    "englishNameTranslation": "Jonas",
    "numberOfAyahs": 109,
    "revelationType": "مكية",
  },
  {
    "number": 11,
    "name": " هُودٍ",
    "englishName": "Hud",
    "englishNameTranslation": "Hud",
    "numberOfAyahs": 123,
    "revelationType": "مكية",
  },
  {
    "number": 12,
    "name": " يُوسُفَ",
    "englishName": "Yusuf",
    "englishNameTranslation": "Joseph",
    "numberOfAyahs": 111,
    "revelationType": "مكية",
  },
  {
    "number": 13,
    "name": " الرَّعۡدِ",
    "englishName": "Ar-Ra'd",
    "englishNameTranslation": "The Thunder",
    "numberOfAyahs": 43,
    "revelationType": "مدنية",
  },
  {
    "number": 14,
    "name": " إِبۡرَاهِيمَ",
    "englishName": "Ibrahim",
    "englishNameTranslation": "Abraham",
    "numberOfAyahs": 52,
    "revelationType": "مكية",
  },
  {
    "number": 15,
    "name": " الحِجۡرِ",
    "englishName": "Al-Hijr",
    "englishNameTranslation": "The Rock",
    "numberOfAyahs": 99,
    "revelationType": "مكية",
  },
  {
    "number": 16,
    "name": " النَّحۡلِ",
    "englishName": "An-Nahl",
    "englishNameTranslation": "The Bee",
    "numberOfAyahs": 128,
    "revelationType": "مكية",
  },
  {
    "number": 17,
    "name": " الإِسۡرَاءِ",
    "englishName": "Al-Israa",
    "englishNameTranslation": "The Night Journey",
    "numberOfAyahs": 111,
    "revelationType": "مكية",
  },
  {
    "number": 18,
    "name": " الكَهۡفِ",
    "englishName": "Al-Kahf",
    "englishNameTranslation": "The Cave",
    "numberOfAyahs": 110,
    "revelationType": "مكية",
  },
  {
    "number": 19,
    "name": " مَرۡيَمَ",
    "englishName": "Maryam",
    "englishNameTranslation": "Mary",
    "numberOfAyahs": 98,
    "revelationType": "مكية",
  },
  {
    "number": 20,
    "name": " طه",
    "englishName": "Taa-Haa",
    "englishNameTranslation": "Taa-Haa",
    "numberOfAyahs": 135,
    "revelationType": "مكية",
  },
  {
    "number": 21,
    "name": " الأَنبِيَاءِ",
    "englishName": "Al-Anbiyaa",
    "englishNameTranslation": "The Prophets",
    "numberOfAyahs": 112,
    "revelationType": "مكية",
  },
  {
    "number": 22,
    "name": " الحَجِّ",
    "englishName": "Al-Hajj",
    "englishNameTranslation": "The Pilgrimage",
    "numberOfAyahs": 78,
    "revelationType": "مدنية",
  },
  {
    "number": 23,
    "name": " المُؤۡمِنُونَ",
    "englishName": "Al-Muminoon",
    "englishNameTranslation": "The Believers",
    "numberOfAyahs": 118,
    "revelationType": "مكية",
  },
  {
    "number": 24,
    "name": " النُّورِ",
    "englishName": "An-Noor",
    "englishNameTranslation": "The Light",
    "numberOfAyahs": 64,
    "revelationType": "مدنية",
  },
  {
    "number": 25,
    "name": " الفُرۡقَانِ",
    "englishName": "Al-Furqaan",
    "englishNameTranslation": "The Criterion",
    "numberOfAyahs": 77,
    "revelationType": "مكية",
  },
  {
    "number": 26,
    "name": " الشُّعَرَاءِ",
    "englishName": "Ash-Shu'araa",
    "englishNameTranslation": "The Poets",
    "numberOfAyahs": 227,
    "revelationType": "مكية",
  },
  {
    "number": 27,
    "name": " النَّمۡلِ",
    "englishName": "An-Naml",
    "englishNameTranslation": "The Ant",
    "numberOfAyahs": 93,
    "revelationType": "مكية",
  },
  {
    "number": 28,
    "name": " القَصَصِ",
    "englishName": "Al-Qasas",
    "englishNameTranslation": "The Stories",
    "numberOfAyahs": 88,
    "revelationType": "مكية",
  },
  {
    "number": 29,
    "name": " العَنكَبُوتِ",
    "englishName": "Al-Ankaboot",
    "englishNameTranslation": "The Spider",
    "numberOfAyahs": 69,
    "revelationType": "مكية",
  },
  {
    "number": 30,
    "name": " الرُّومِ",
    "englishName": "Ar-Room",
    "englishNameTranslation": "The Romans",
    "numberOfAyahs": 60,
    "revelationType": "مكية",
  },
  {
    "number": 31,
    "name": " لُقۡمَانَ",
    "englishName": "Luqman",
    "englishNameTranslation": "Luqman",
    "numberOfAyahs": 34,
    "revelationType": "مكية",
  },
  {
    "number": 32,
    "name": " السَّجۡدَةِ",
    "englishName": "As-Sajda",
    "englishNameTranslation": "The Prostration",
    "numberOfAyahs": 30,
    "revelationType": "مكية",
  },
  {
    "number": 33,
    "name": " الأَحۡزَابِ",
    "englishName": "Al-Ahzaab",
    "englishNameTranslation": "The Clans",
    "numberOfAyahs": 73,
    "revelationType": "مدنية",
  },
  {
    "number": 34,
    "name": " سَبَإٍ",
    "englishName": "Saba",
    "englishNameTranslation": "Sheba",
    "numberOfAyahs": 54,
    "revelationType": "مكية",
  },
  {
    "number": 35,
    "name": " فَاطِرٍ",
    "englishName": "Faatir",
    "englishNameTranslation": "The Originator",
    "numberOfAyahs": 45,
    "revelationType": "مكية",
  },
  {
    "number": 36,
    "name": " يسٓ",
    "englishName": "Yaseen",
    "englishNameTranslation": "Yaseen",
    "numberOfAyahs": 83,
    "revelationType": "مكية",
  },
  {
    "number": 37,
    "name": " الصَّافَّاتِ",
    "englishName": "As-Saaffaat",
    "englishNameTranslation": "Those drawn up in Ranks",
    "numberOfAyahs": 182,
    "revelationType": "مكية",
  },
  {
    "number": 38,
    "name": " صٓ",
    "englishName": "Saad",
    "englishNameTranslation": "The letter Saad",
    "numberOfAyahs": 88,
    "revelationType": "مكية",
  },
  {
    "number": 39,
    "name": " الزُّمَرِ",
    "englishName": "Az-Zumar",
    "englishNameTranslation": "The Groups",
    "numberOfAyahs": 75,
    "revelationType": "مكية",
  },
  {
    "number": 40,
    "name": " غَافِرٍ",
    "englishName": "Ghafir",
    "englishNameTranslation": "The Forgiver",
    "numberOfAyahs": 85,
    "revelationType": "مكية",
  },
  {
    "number": 41,
    "name": " فُصِّلَتۡ",
    "englishName": "Fussilat",
    "englishNameTranslation": "Explained in detail",
    "numberOfAyahs": 54,
    "revelationType": "مكية",
  },
  {
    "number": 42,
    "name": " الشُّورَىٰ",
    "englishName": "Ash-Shura",
    "englishNameTranslation": "Consultation",
    "numberOfAyahs": 53,
    "revelationType": "مكية",
  },
  {
    "number": 43,
    "name": " الزُّخۡرُفِ",
    "englishName": "Az-Zukhruf",
    "englishNameTranslation": "Ornaments of gold",
    "numberOfAyahs": 89,
    "revelationType": "مكية",
  },
  {
    "number": 44,
    "name": " الدُّخَانِ",
    "englishName": "Ad-Dukhaan",
    "englishNameTranslation": "The Smoke",
    "numberOfAyahs": 59,
    "revelationType": "مكية",
  },
  {
    "number": 45,
    "name": " الجَاثِيَةِ",
    "englishName": "Al-Jaathiya",
    "englishNameTranslation": "Crouching",
    "numberOfAyahs": 37,
    "revelationType": "مكية",
  },
  {
    "number": 46,
    "name": " الأَحۡقَافِ",
    "englishName": "Al-Ahqaf",
    "englishNameTranslation": "The Dunes",
    "numberOfAyahs": 35,
    "revelationType": "مكية",
  },
  {
    "number": 47,
    "name": " مُحَمَّدٍ",
    "englishName": "Muhammad",
    "englishNameTranslation": "Muhammad",
    "numberOfAyahs": 38,
    "revelationType": "مدنية",
  },
  {
    "number": 48,
    "name": " الفَتۡحِ",
    "englishName": "Al-Fath",
    "englishNameTranslation": "The Victory",
    "numberOfAyahs": 29,
    "revelationType": "مدنية",
  },
  {
    "number": 49,
    "name": " الحُجُرَاتِ",
    "englishName": "Al-Hujuraat",
    "englishNameTranslation": "The Inner Apartments",
    "numberOfAyahs": 18,
    "revelationType": "مدنية",
  },
  {
    "number": 50,
    "name": " قٓ",
    "englishName": "Qaaf",
    "englishNameTranslation": "The letter Qaaf",
    "numberOfAyahs": 45,
    "revelationType": "مكية",
  },
  {
    "number": 51,
    "name": " الذَّارِيَاتِ",
    "englishName": "Adh-Dhaariyat",
    "englishNameTranslation": "The Winnowing Winds",
    "numberOfAyahs": 60,
    "revelationType": "مكية",
  },
  {
    "number": 52,
    "name": " الطُّورِ",
    "englishName": "At-Tur",
    "englishNameTranslation": "The Mount",
    "numberOfAyahs": 49,
    "revelationType": "مكية",
  },
  {
    "number": 53,
    "name": " النَّجۡمِ",
    "englishName": "An-Najm",
    "englishNameTranslation": "The Star",
    "numberOfAyahs": 62,
    "revelationType": "مكية",
  },
  {
    "number": 54,
    "name": " القَمَرِ",
    "englishName": "Al-Qamar",
    "englishNameTranslation": "The Moon",
    "numberOfAyahs": 55,
    "revelationType": "مكية",
  },
  {
    "number": 55,
    "name": " الرَّحۡمَٰن",
    "englishName": "Ar-Rahmaan",
    "englishNameTranslation": "The Beneficent",
    "numberOfAyahs": 78,
    "revelationType": "مدنية",
  },
  {
    "number": 56,
    "name": " الوَاقِعَةِ",
    "englishName": "Al-Waaqia",
    "englishNameTranslation": "The Inevitable",
    "numberOfAyahs": 96,
    "revelationType": "مكية",
  },
  {
    "number": 57,
    "name": " الحَدِيدِ",
    "englishName": "Al-Hadid",
    "englishNameTranslation": "The Iron",
    "numberOfAyahs": 29,
    "revelationType": "مدنية",
  },
  {
    "number": 58,
    "name": " المُجَادلَةِ",
    "englishName": "Al-Mujaadila",
    "englishNameTranslation": "The Pleading Woman",
    "numberOfAyahs": 22,
    "revelationType": "مدنية",
  },
  {
    "number": 59,
    "name": " الحَشۡرِ",
    "englishName": "Al-Hashr",
    "englishNameTranslation": "The Exile",
    "numberOfAyahs": 24,
    "revelationType": "مدنية",
  },
  {
    "number": 60,
    "name": " المُمۡتَحنَةِ",
    "englishName": "Al-Mumtahana",
    "englishNameTranslation": "She that is to be examined",
    "numberOfAyahs": 13,
    "revelationType": "مدنية",
  },
  {
    "number": 61,
    "name": " الصَّفِّ",
    "englishName": "As-Saff",
    "englishNameTranslation": "The Ranks",
    "numberOfAyahs": 14,
    "revelationType": "مدنية",
  },
  {
    "number": 62,
    "name": " الجُمُعَةِ",
    "englishName": "Al-Jumu'a",
    "englishNameTranslation": "Friday",
    "numberOfAyahs": 11,
    "revelationType": "مدنية",
  },
  {
    "number": 63,
    "name": " المُنَافِقُونَ",
    "englishName": "Al-Munaafiqoon",
    "englishNameTranslation": "The Hypocrites",
    "numberOfAyahs": 11,
    "revelationType": "مدنية",
  },
  {
    "number": 64,
    "name": " التَّغَابُنِ",
    "englishName": "At-Taghaabun",
    "englishNameTranslation": "Mutual Disillusion",
    "numberOfAyahs": 18,
    "revelationType": "مدنية",
  },
  {
    "number": 65,
    "name": " الطَّلَاقِ",
    "englishName": "At-Talaaq",
    "englishNameTranslation": "Divorce",
    "numberOfAyahs": 12,
    "revelationType": "مدنية",
  },
  {
    "number": 66,
    "name": " التَّحۡرِيمِ",
    "englishName": "At-Tahrim",
    "englishNameTranslation": "The Prohibition",
    "numberOfAyahs": 12,
    "revelationType": "مدنية",
  },
  {
    "number": 67,
    "name": " المُلۡكِ",
    "englishName": "Al-Mulk",
    "englishNameTranslation": "The Sovereignty",
    "numberOfAyahs": 30,
    "revelationType": "مكية",
  },
  {
    "number": 68,
    "name": " القَلَمِ",
    "englishName": "Al-Qalam",
    "englishNameTranslation": "The Pen",
    "numberOfAyahs": 52,
    "revelationType": "مكية",
  },
  {
    "number": 69,
    "name": " الحَاقَّةِ",
    "englishName": "Al-Haaqqa",
    "englishNameTranslation": "The Reality",
    "numberOfAyahs": 52,
    "revelationType": "مكية",
  },
  {
    "number": 70,
    "name": " المَعَارِجِ",
    "englishName": "Al-Ma'aarij",
    "englishNameTranslation": "The Ascending Stairways",
    "numberOfAyahs": 44,
    "revelationType": "مكية",
  },
  {
    "number": 71,
    "name": " نُوحٍ",
    "englishName": "Nooh",
    "englishNameTranslation": "Noah",
    "numberOfAyahs": 28,
    "revelationType": "مكية",
  },
  {
    "number": 72,
    "name": " الجِنِّ",
    "englishName": "Al-Jinn",
    "englishNameTranslation": "The Jinn",
    "numberOfAyahs": 28,
    "revelationType": "مكية",
  },
  {
    "number": 73,
    "name": " المُزَّمِّلِ",
    "englishName": "Al-Muzzammil",
    "englishNameTranslation": "The Enshrouded One",
    "numberOfAyahs": 20,
    "revelationType": "مكية",
  },
  {
    "number": 74,
    "name": " المُدَّثِّرِ",
    "englishName": "Al-Muddaththir",
    "englishNameTranslation": "The Cloaked One",
    "numberOfAyahs": 56,
    "revelationType": "مكية",
  },
  {
    "number": 75,
    "name": " القِيَامَةِ",
    "englishName": "Al-Qiyaama",
    "englishNameTranslation": "The Resurrection",
    "numberOfAyahs": 40,
    "revelationType": "مكية",
  },
  {
    "number": 76,
    "name": " الإِنسَانِ",
    "englishName": "Al-Insaan",
    "englishNameTranslation": "Man",
    "numberOfAyahs": 31,
    "revelationType": "مدنية",
  },
  {
    "number": 77,
    "name": " المُرۡسَلَاتِ",
    "englishName": "Al-Mursalaat",
    "englishNameTranslation": "The Emissaries",
    "numberOfAyahs": 50,
    "revelationType": "مكية",
  },
  {
    "number": 78,
    "name": " النَّبَإِ",
    "englishName": "An-Naba",
    "englishNameTranslation": "The Announcement",
    "numberOfAyahs": 40,
    "revelationType": "مكية",
  },
  {
    "number": 79,
    "name": " النَّازِعَاتِ",
    "englishName": "An-Naazi'aat",
    "englishNameTranslation": "Those who drag forth",
    "numberOfAyahs": 46,
    "revelationType": "مكية",
  },
  {
    "number": 80,
    "name": " عَبَسَ",
    "englishName": "Abasa",
    "englishNameTranslation": "He frowned",
    "numberOfAyahs": 42,
    "revelationType": "مكية",
  },
  {
    "number": 81,
    "name": " التَّكۡوِيرِ",
    "englishName": "At-Takwir",
    "englishNameTranslation": "The Overthrowing",
    "numberOfAyahs": 29,
    "revelationType": "مكية",
  },
  {
    "number": 82,
    "name": " الانفِطَارِ",
    "englishName": "Al-Infitaar",
    "englishNameTranslation": "The Cleaving",
    "numberOfAyahs": 19,
    "revelationType": "مكية",
  },
  {
    "number": 83,
    "name": " المُطَفِّفِينَ",
    "englishName": "Al-Mutaffifin",
    "englishNameTranslation": "Defrauding",
    "numberOfAyahs": 36,
    "revelationType": "مكية",
  },
  {
    "number": 84,
    "name": " الانشِقَاقِ",
    "englishName": "Al-Inshiqaaq",
    "englishNameTranslation": "The Splitting Open",
    "numberOfAyahs": 25,
    "revelationType": "مكية",
  },
  {
    "number": 85,
    "name": " البُرُوجِ",
    "englishName": "Al-Burooj",
    "englishNameTranslation": "The Constellations",
    "numberOfAyahs": 22,
    "revelationType": "مكية",
  },
  {
    "number": 86,
    "name": " الطَّارِقِ",
    "englishName": "At-Taariq",
    "englishNameTranslation": "The Morning Star",
    "numberOfAyahs": 17,
    "revelationType": "مكية",
  },
  {
    "number": 87,
    "name": " الأَعۡلَىٰ",
    "englishName": "Al-A'laa",
    "englishNameTranslation": "The Most High",
    "numberOfAyahs": 19,
    "revelationType": "مكية",
  },
  {
    "number": 88,
    "name": " الغَاشِيَةِ",
    "englishName": "Al-Ghaashiya",
    "englishNameTranslation": "The Overwhelming",
    "numberOfAyahs": 26,
    "revelationType": "مكية",
  },
  {
    "number": 89,
    "name": " الفَجۡرِ",
    "englishName": "Al-Fajr",
    "englishNameTranslation": "The Dawn",
    "numberOfAyahs": 30,
    "revelationType": "مكية",
  },
  {
    "number": 90,
    "name": " البَلَدِ",
    "englishName": "Al-Balad",
    "englishNameTranslation": "The City",
    "numberOfAyahs": 20,
    "revelationType": "مكية",
  },
  {
    "number": 91,
    "name": " الشَّمۡسِ",
    "englishName": "Ash-Shams",
    "englishNameTranslation": "The Sun",
    "numberOfAyahs": 15,
    "revelationType": "مكية",
  },
  {
    "number": 92,
    "name": " اللَّيۡلِ",
    "englishName": "Al-Lail",
    "englishNameTranslation": "The Night",
    "numberOfAyahs": 21,
    "revelationType": "مكية",
  },
  {
    "number": 93,
    "name": " الضُّحَىٰ",
    "englishName": "Ad-Dhuhaa",
    "englishNameTranslation": "The Morning Hours",
    "numberOfAyahs": 11,
    "revelationType": "مكية",
  },
  {
    "number": 94,
    "name": " الشَّرۡحِ",
    "englishName": "Ash-Sharh",
    "englishNameTranslation": "The Consolation",
    "numberOfAyahs": 8,
    "revelationType": "مكية",
  },
  {
    "number": 95,
    "name": " التِّينِ",
    "englishName": "At-Tin",
    "englishNameTranslation": "The Fig",
    "numberOfAyahs": 8,
    "revelationType": "مكية",
  },
  {
    "number": 96,
    "name": " العَلَقِ",
    "englishName": "Al-Alaq",
    "englishNameTranslation": "The Clot",
    "numberOfAyahs": 19,
    "revelationType": "مكية",
  },
  {
    "number": 97,
    "name": " القَدۡرِ",
    "englishName": "Al-Qadr",
    "englishNameTranslation": "The Power, Fate",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
  },
  {
    "number": 98,
    "name": " البَيِّنَةِ",
    "englishName": "Al-Bayyina",
    "englishNameTranslation": "The Evidence",
    "numberOfAyahs": 8,
    "revelationType": "مدنية",
  },
  {
    "number": 99,
    "name": " الزَّلۡزَلَةِ",
    "englishName": "Az-Zalzala",
    "englishNameTranslation": "The Earthquake",
    "numberOfAyahs": 8,
    "revelationType": "مدنية",
  },
  {
    "number": 100,
    "name": " العَادِيَاتِ",
    "englishName": "Al-Aadiyaat",
    "englishNameTranslation": "The Chargers",
    "numberOfAyahs": 11,
    "revelationType": "مكية",
  },
  {
    "number": 101,
    "name": " القَارِعَةِ",
    "englishName": "Al-Qaari'a",
    "englishNameTranslation": "The Calamity",
    "numberOfAyahs": 11,
    "revelationType": "مكية",
  },
  {
    "number": 102,
    "name": " التَّكَاثُرِ",
    "englishName": "At-Takaathur",
    "englishNameTranslation": "Competition",
    "numberOfAyahs": 8,
    "revelationType": "مكية",
  },
  {
    "number": 103,
    "name": " العَصۡرِ",
    "englishName": "Al-Asr",
    "englishNameTranslation": "The Declining Day, Epoch",
    "numberOfAyahs": 3,
    "revelationType": "مكية",
  },
  {
    "number": 104,
    "name": " الهُمَزَةِ",
    "englishName": "Al-Humaza",
    "englishNameTranslation": "The Traducer",
    "numberOfAyahs": 9,
    "revelationType": "مكية",
  },
  {
    "number": 105,
    "name": " الفِيلِ",
    "englishName": "Al-Fil",
    "englishNameTranslation": "The Elephant",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
  },
  {
    "number": 106,
    "name": " قُرَيۡشٍ",
    "englishName": "Quraish",
    "englishNameTranslation": "Quraysh",
    "numberOfAyahs": 4,
    "revelationType": "مكية",
  },
  {
    "number": 107,
    "name": " المَاعُونِ",
    "englishName": "Al-Maa'un",
    "englishNameTranslation": "Almsgiving",
    "numberOfAyahs": 7,
    "revelationType": "مكية",
  },
  {
    "number": 108,
    "name": " الكَوۡثَرِ",
    "englishName": "Al-Kawthar",
    "englishNameTranslation": "Abundance",
    "numberOfAyahs": 3,
    "revelationType": "مكية",
  },
  {
    "number": 109,
    "name": " الكَافِرُونَ",
    "englishName": "Al-Kaafiroon",
    "englishNameTranslation": "The Disbelievers",
    "numberOfAyahs": 6,
    "revelationType": "مكية",
  },
  {
    "number": 110,
    "name": " النَّصۡرِ",
    "englishName": "An-Nasr",
    "englishNameTranslation": "Divine Support",
    "numberOfAyahs": 3,
    "revelationType": "مدنية",
  },
  {
    "number": 111,
    "name": " المَسَدِ",
    "englishName": "Al-Masad",
    "englishNameTranslation": "The Palm Fibre",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
  },
  {
    "number": 112,
    "name": " الإِخۡلَاصِ",
    "englishName": "Al-Ikhlaas",
    "englishNameTranslation": "Sincerity",
    "numberOfAyahs": 4,
    "revelationType": "مكية",
  },
  {
    "number": 113,
    "name": " الفَلَقِ",
    "englishName": "Al-Falaq",
    "englishNameTranslation": "The Dawn",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
  },
  {
    "number": 114,
    "name": " النَّاسِ",
    "englishName": "An-Naas",
    "englishNameTranslation": "Mankind",
    "numberOfAyahs": 6,
    "revelationType": "مكية",
  },
];

const Map<String, List<Map<String, dynamic>>> athkarList = {
  "morning": [
    {
      "id": "athkar#1.1",
      "text":
          "أعوذ بالـلـه من الشيطان الـرجـيم ﴿اللهُ لاَ إِلَٰهَ إِلاَّ هُـوَ الْـحَيُّ الْـقَيُّومُ لاَ تَأخذُهُ سنَةٌ ولا نومٌ لهُ ما في السَّمَاوَاتِ وما في الأَرضِ من ذا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بإِذنهِ يعْلَمُ ما بينَ أيدِيهِمْ وما خلفَهُمْ ولا يُحيطُونَ بِشيءٍ مِّن عِلْمِهِ إِلاَّ بِمَا شَاء وَسعَ كُرْسيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤودُهُ حِفظُهُمَا وهوَ العَليُّ العَظيمُ﴾ [البقرة: ٢٥٥].",
      "counter": 1,
    },
    {
      "id": "athkar#1.2",
      "text":
          "بسم الله الرحمن الرحيم ﴿قُل هُوَ اللهُ أَحَدٌ * اللهُ الصَّمَدُ * لم يلد ولم يولد * ولم يَكُن لَهُ كُفُواً أَحَدٌ﴾ [الإخلاص: ١-٤].",
      "counter": 3,
    },
    {
      "id": "athkar#1.3",
      "text":
          "بسم الله الرحمن الرحيم ﴿قُل أَعوذُ بربِّ الفَلَقِ * مِن شر ما خَلَقَ * ومِن شر غاسِقٍ إِذا وَقَبَ * ومِن شر النَّفّاثاتِ فِي العُقَدِ * ومِن شر حاسِدٍ إِذا حَسَدَ﴾ [الفلق: ١-٥].",
      "counter": 3,
    },
    {
      "id": "athkar#1.4",
      "text":
          "بسم الله الرحمن الرحيم ﴿قُل أعوذُ بربِّ النّاسِ * ملكِ النّاسِ * إلهِ النّاسِ * من شر الوَسواسِ الخَنّاسِ * الذي يوسوِسُ في صدورِ النّاسِ * منَ الجِنَّةِ والنّاسِ﴾ [الناس: ١-٦].",
      "counter": 3,
    },
    {
      "id": "athkar#1.5",
      "text":
          "أصـبَحنا وأصـبَحَ المُـلكُ لله والحَمدُ لله، لا إلهَ إلا اللهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمـد، وهو على كل شيءٍ قدير، رَبِّ أسـألُـكَ خـيرَ ما في هـذا اليوم وخـيرَ ما بَعْـدَه، وأعـوذُ بِكَ من شـر ما في هـذا اليوم وشر ما بَعْـدَه، رَبِّ أعـوذُ بِكَ من الْكَسَـلِ وسـوءِ الكِـبَر، رَبِّ أعـوذُ بِكَ من عـذابٍ في النّـارِ وعـذابٍ في القَـبْر.",
      "counter": 1,
    },
    {
      "id": "athkar#1.6",
      "text":
          "اللَّهُمَّ بِكَ أصبَحنا، وبِكَ أمسَينا، وبِكَ نحيا وبِكَ نموتُ وإليكَ النُّشورُ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.7",
      "text":
          "اللَّهُمَّ أنتَ رَبيِّ لا إله إلا أنتَ، خَلَقتنَيِ وأنا عَبدُكَ، وأنا على عَهْدِكَ ووعدِكَ ما استَطَعتُ، أعوذُ بكَ من شر ما صَنَعتُ، أبوءُ لكَ بنعمَتِكَ علَيَّ، وأبوءُ بذَنْبِي فاغْفِرْ لي فَإنَّهُ لَا يَغفِرُ الذُّنُوبَ إلا أنتَ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.8",
      "text":
          "اللَّهُمَّ إني أصبَحتُ أُشهِدُكَ، وأُشهِدُ حَمَلةَ عَرشِكَ، ومَلائِكَتَكَ، وجميعَ خَلقِكَ: أنكَ أنتَ اللهُ لا إلهَ إلا أنتَ وَحدَكَ لا شَرِيكَ لَكَ، وأن مُحمَّدًا عبدُكَ ورسولُكَ.",
      "counter": 4,
    },
    {
      "id": "athkar#1.9",
      "text":
          "اللَّهُمَّ ما أصبحَ بي من نعمةٍ أو بأحدٍ من خلقِكَ فمنكَ وحدَكَ لا شريكَ لكَ فلكَ الحمدُ ولكَ الشُّكرُ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.10",
      "text":
          "اللَّهُمَّ عافِني في بدَني، اللَّهُمَّ عافِني في سمعي، اللَّهُمَّ عافِني في بصري، لا إلهَ إلا أنت. اللَّهُمَّ إنِّي أعوذُ بِكَ منَ الكُفْرِ، والفقرِ، وأعوذُ بكَ من عذابِ القبرِ، لا إلهَ إلا أنت.",
      "counter": 3,
    },
    {
      "id": "athkar#1.11",
      "text":
          "حَسْبِيَ اللهُ لا إلهَ إلا هُوَ علَيهِ تَوَكَّلتُ وهُوَ رَبُّ العَرْشِ العَظيم.",
      "counter": 7,
    },
    {
      "id": "athkar#1.12",
      "text":
          "اللَّهُمَّ إني أسألكَ العَفْوَ والعافيَةَ في الدنيا والآخرةِ، اللَّهُمَّ إني أسألكَ العَفْوَ والعافيَةَ: في دينِي ودُنيَايَ وأهلِي، ومالِي، اللَّهُمَّ اسْتُرْ عَوْراتي، وآمِنْ رَوْعاتي، اللَّهُمَّ احْفَظْنِي من بَينِ يَدَيَّ، ومن خَلْفي، وعن يَميني، وعن شِمالي، ومن فَوْقي، وأعوذُ بِعَظَمَتِكَ أن أُغْتالَ من تَحتي.",
      "counter": 1,
    },
    {
      "id": "athkar#1.13",
      "text":
          "اللَّهُمَّ عالِمَ الغَيْبِ والشَّهادَةِ فاطِرَ السمواتِ والأرضِ، رَبَّ كل شيءٍ ومَليكَهُ، أشْهَدُ أن لا إلهَ إلا أنتَ، أعوذُ بِكَ من شر نَفْسي، ومن شر الشيطانِ وشَرَكِهِ، وأن أَقْتَرِفَ على نفسي سُوءاً، أو أجُرَّهُ إلى مُسلِمٍ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.14",
      "text":
          "بِسْمِ اللهِ الذي لا يَضُرُّ مع اسمهِ شيءٌ في الأرضِ ولا في السماءِ وهو السَّميعُ العَليمُ.",
      "counter": 3,
    },
    {
      "id": "athkar#1.15",
      "text":
          "رضيت بالله رباً، وبالإسلام ديناً، وبمحمد صلى الله عليه وسلم نبياً.",
      "counter": 3,
    },
    {
      "id": "athkar#1.16",
      "text":
          "يا حَيُّ يا قَيُّومُ بِرَحْمَتِكَ أسْتَغيثُ أصلِحْ لي شأنيَ كلهُ ولا تَكِلْني إلى نَفْسي طَرْفَةَ عينٍ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.17",
      "text":
          "أصبَحْنا وأصْبَحَ المُلْكُ لِلهِ رَبِّ العالمينَ، اللَّهُـمَّ إني أسألكَ خيرَ هذا اليومِ: فَتْحَهُ، ونَصْرَهُ، ونورَهُ، وبَرَكَتَهُ، وهُدَاهُ، وأعوذُ بكَ من شر ما فيهِ وشر ما بعدَهُ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.18",
      "text":
          "أصبَحْنا على فِطْرَةِ الإسلامِ، وعلى كَلِمَةِ الإخلاصِ، وعلى دينِ نَبِيِّنَا محمدٍ صلى الله عليه وسلم، وعلى مِلَّةِ أبينا إبراهيمَ، حَنيفاً مُسلماً وما كان من المُشرِكينَ.",
      "counter": 1,
    },
    {
      "id": "athkar#1.19",
      "text": "سُبْحانَ اللهِ وبِحَمْدِهِ.",
      "counter": 100,
    },
    {
      "id": "athkar#1.20",
      "text":
          "لا إلهَ إلا اللهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُلْكُ ولهُ الحَمْدُ، وهوَ على كل شيءٍ قَديرٌ. (عشرَ مرات)، أو (مرةً واحدةً عندَ الكَسَلِ).",
      "counter": 10,
    },
    {
      "id": "athkar#1.21",
      "text":
          "لا إلهَ إلا اللهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُلْكُ ولهُ الحَمْدُ، وهوَ على كل شيءٍ قَديرٌ.",
      "counter": 100,
    },
    {
      "id": "athkar#1.22",
      "text":
          "سُبْحانَ اللهِ وبِحَمْدِهِ: عَدَدَ خَلْقِهِ، ورِضا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، ومِدَادَ كَلِمَاتِهِ.",
      "counter": 3,
    },
    {
      "id": "athkar#1.23",
      "text":
          "اللَّهُمَّ إني أسألكَ عِلْماً نافِعاً، ورِزْقاً طَيِّباً، وعملاً مُتَقَبَّلاً.",
      "counter": 1,
    },
    {
      "id": "athkar#1.24",
      "text": "أَستَغْفِرُ اللهَ وأتُوبُ إليهِ.",
      "counter": 100,
    },
    {
      "id": "athkar#1.25",
      "text": "اللَّهُمَّ صَلِّ وسَلِّمْ على نَبَيِّنَا محمدٍ.",
      "counter": 10,
    },
  ],
  "night": [
    {
      "id": "athkar#2.1",
      "text":
          "أعوذ بالـلـه من الشيطان الـرجـيم ﴿اللَّهُ لاَ إِلَٰهَ إِلاَّ هُـوَ الْـحَيُّ الْـقَيُّومُ لاَ تَأخذُهُ سنَةٌ ولا نومٌ لهُ ما في السَّمَاوَاتِ وما في الأَرضِ من ذا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بإِذنهِ يعْلَمُ ما بينَ أيدِيهِمْ وما خلفَهُمْ ولا يُحيطُونَ بِشيءٍ مِّن عِلْمِهِ إِلاَّ بِمَا شَاء وَسعَ كُرْسيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤودُهُ حِفظُهُمَا وهوَ العَليُّ العَظيمُ﴾ [البقرة: ٢٥٥].",
      "counter": 1,
    },
    {
      "id": "athkar#2.2",
      "text":
          "بسم الله الرحمن الرحيم ﴿قُل هُوَ اللَّهُ أَحَدٌ * اللَّهُ الصَّمَدُ * لم يلد ولم يولد * ولم يَكُن لَهُ كُفُواً أَحَدٌ﴾ [الإخلاص: ١-٤].",
      "counter": 3,
    },
    {
      "id": "athkar#2.3",
      "text":
          "بسم الله الرحمن الرحيم ﴿قُل أَعوذُ بربِّ الفَلَقِ * مِن شر ما خَلَقَ * ومِن شر غاسِقٍ إِذا وَقَبَ * ومِن شر النَّفّاثاتِ فِي العُقَدِ * ومِن شر حاسِدٍ إِذا حَسَدَ﴾ [الفلق: ١-٥].",
      "counter": 3,
    },
    {
      "id": "athkar#2.4",
      "text":
          "بسم الله الرحمن الرحيم ﴿قُل أعوذُ بربِّ النّاسِ * ملكِ النّاسِ * إلهِ النّاسِ * من شر الوَسواسِ الخَنّاسِ * الذي يوسوِسُ في صدورِ النّاسِ * منَ الجِنَّةِ والنّاسِ﴾ [الناس: ١-٦].",
      "counter": 3,
    },
    {
      "id": "athkar#2.5",
      "text":
          "أمسَينا وأمسَى المُـلكُ لله والحَمدُ لله، لا إلهَ إلا اللهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمـد، وهو على كل شيءٍ قدير، رَبِّ أسـألُـكَ خـيرَ ما في هذه الليلة وخـيرَ ما بعدها، وأعـوذُ بِكَ من شـر ما في هذه الليلة وشر ما بعدها، رَبِّ أعـوذُ بِكَ من الْكَسَـلِ وسـوءِ الكِـبَر، رَبِّ أعـوذُ بِكَ من عـذابٍ في النّـارِ وعـذابٍ في القَـبْر.",
      "counter": 1,
    },
    {
      "id": "athkar#2.6",
      "text":
          "اللَّهُمَّ بِكَ أمسَينا، وبِكَ أصبَحنا، وبِكَ نحيا، وبِكَ نموتُ وإليكَ المصيرُ.",
      "counter": 1,
    },
    {
      "id": "athkar#2.7",
      "text":
          "اللَّهُمَّ أنتَ رَبيِّ لا إله إلا أنتَ، خَلَقتنَيِ وأنا عَبدُكَ، وأنا على عَهْدِكَ ووعدِكَ ما استَطَعتُ، أعوذُ بكَ من شر ما صَنَعتُ، أبوءُ لكَ بنعمَتِكَ علَيَّ، وأبوءُ بذَنْبِي فاغْفِرْ لي فَإنَّهُ لَا يَغفِرُ الذُّنُوبَ إلا أنتَ.",
      "counter": 1,
    },
    {
      "id": "athkar#2.8",
      "text":
          " اللَّهُمَّ إني أمسَيت أُشهِدُكَ، وأُشهِدُ حَمَلةَ عَرشِكَ، ومَلائِكَتَكَ، وجميعَ خَلقِكَ: أنكَ أنتَ اللهُ لا إلهَ إلا أنتَ وَحدَكَ لا شَرِيكَ لَكَ، وأن مُحمَّدًا عبدُكَ ورسولُكَ.",
      "counter": 4,
    },
    {
      "id": "athkar#2.9",
      "text":
          "اللَّهُمَّ ما أمسَى بي من نعمةٍ أو بأحدٍ من خلقِكَ فمنكَ وحدَكَ لا شريكَ لكَ فلكَ الحمدُ ولكَ الشُّكرُ.",
      "counter": 1,
    },
    {
      "id": "athkar#2.10",
      "text":
          "اللَّهُمَّ عافِني في بدَني، اللَّهُمَّ عافِني في سمعي، اللَّهُمَّ عافِني في بصري، لا إلهَ إلا أنت. اللَّهُمَّ إنِّي أعوذُ بِكَ منَ الكُفْرِ، والفقرِ، وأعوذُ بكَ من عذابِ القبرِ، لا إلهَ إلا أنت.",
      "counter": 3,
    },
    {
      "id": "athkar#2.11",
      "text":
          "حَسْبِيَ اللهُ لا إلهَ إلا هُوَ علَيهِ تَوَكَّلتُ وهُوَ رَبُّ العَرْشِ العَظيم.",
      "counter": 7,
    },
    {
      "id": "athkar#2.12",
      "text":
          "اللَّهُمَّ إني أسألكَ العَفْوَ والعافيَةَ في الدنيا والآخرةِ، اللَّهُمَّ إني أسألكَ العَفْوَ والعافيَةَ: في دينِي ودُنيَايَ وأهلِي، ومالِي، اللَّهُمَّ اسْتُرْ عَوْراتي، وآمِنْ رَوْعاتي، اللَّهُمَّ احْفَظْنِي من بَينِ يَدَيَّ، ومن خَلْفي، وعن يَميني، وعن شِمالي، ومن فَوْقي، وأعوذُ بِعَظَمَتِكَ أن أُغْتالَ من تَحتي.",
      "counter": 1,
    },
    {
      "id": "athkar#2.13",
      "text":
          "اللَّهُمَّ عالِمَ الغَيْبِ والشَّهادَةِ فاطِرَ السمواتِ والأرضِ، رَبَّ كل شيءٍ ومَليكَهُ، أشْهَدُ أن لا إلهَ إلا أنتَ، أعوذُ بِكَ من شر نَفْسي، ومن شر الشيطانِ وشَرَكِهِ، وأن أَقْتَرِفَ على نفسي سُوءاً، أو أجُرَّهُ إلى مُسلِمٍ.",
      "counter": 1,
    },
    {
      "id": "athkar#2.14",
      "text":
          "بِسْمِ اللهِ الذي لا يَضُرُّ مع اسمهِ شيءٌ في الأرضِ ولا في السماءِ وهو السَّميعُ العَليمُ.",
      "counter": 3,
    },
    {
      "id": "athkar#2.15",
      "text":
          "رضيت بالله رباً، وبالإسلام ديناً، وبمحمد صلى الله عليه وسلم نبياً.",
      "counter": 3,
    },
    {
      "id": "athkar#2.16",
      "text":
          "يا حَيُّ يا قَيُّومُ بِرَحْمَتِكَ أسْتَغيثُ أصلِحْ لي شأنيَ كلهُ ولا تَكِلْني إلى نَفْسي طَرْفَةَ عينٍ.",
      "counter": 1,
    },
    {
      "id": "athkar#2.17",
      "text":
          "أمسَينا وأمسَى الملك لِلهِ رَبِّ العالمينَ، اللَّهُـمَّ إني أسألكَ خيرَ هذه الليلة: فَتْحَها، ونَصْرَها، ونورَها، وبَرَكَتَها، وهُدَاها، وأعوذُ بكَ من شر ما فيهِا وشر ما بعدَها.",
      "counter": 1,
    },
    {
      "id": "athkar#2.18",
      "text":
          "أمسَينا على فِطْرَةِ الإسلامِ، وعلى كَلِمَةِ الإخلاصِ، وعلى دينِ نَبِيِّنَا محمدٍ صلى الله عليه وسلم، وعلى مِلَّةِ أبينا إبراهيمَ، حَنيفاً مُسلماً وما كان من المُشرِكينَ.",
      "counter": 1,
    },
    {
      "id": "athkar#2.19",
      "text": "سُبْحانَ اللهِ وبِحَمْدِهِ.",
      "counter": 100,
    },
    {
      "id": "athkar#2.20",
      "text":
          "لا إلهَ إلا اللهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُلْكُ ولهُ الحَمْدُ، وهوَ على كل شيءٍ قَديرٌ.",
      "counter": 10,
    },
    {
      "id": "athkar#2.21",
      "text": "أعوذُ بِكَلِماتِ اللهِ التَّامَّاتِ من شر ما خَلَقَ.",
      "counter": 3,
    },
    {
      "id": "athkar#2.22",
      "text": "اللَّهُمَّ صَلِّ وسَلِّمْ على نَبَيِّنَا محمدٍ.",
      "counter": 10,
    },
  ],
};
